# Project information
site_name: DIPC SLURM training 
site_description: DIPC SLURM training
site_author: DIPC SCC

# Copyright
copyright: Copyright &copy; 2023 DIPC

# Navigation
nav:
  - Home: 0_presentation/index.md
  - Introduction: 1_introduction/index.md
  - Generic Workflow: 2_workflow/index.md
  - First Example: 3_first-example/index.md
  - Job Monitoring: 4_monitoring/index.md
  - Policies and constrains: 5_constrain/index.md
  - Postrun: 6_postrun/index.md
  - Use cases and examples: 7_examples/index.md
  - Advanced usage: 7_advanced/index.md
  - Wrap-Up: 9_wrap-up/index.md

# Configuration
theme:
  name: material
  logo: images/dipc-logo.png 
  favicon: images/favicon.ico
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: custom-dark
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Extra CSS styles
extra_css:
  - stylesheets/extra.css
  - stylesheets/dark-palette.css

# Extensions
markdown_extensions:
  - meta
  - attr_list
  - footnotes
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols:
      fractions: false
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets

# Plugins
plugins:
  - search
  - minify:
      minify_html: true    
